### ISSUE TITLE
Got very different accuracy testing on RAF-DB test set

### ISSUE THREAD

**Issue by HOMGH** [aliprf/Ad-Corre#2]
Salam Ali, thanks for sharing the source codes.
I could successfully test your method on RAF-DB test set using AffectNet_6336.h5 model, but got the following error when trying to use other models e.g., RafDB_8696.h5 and Fer2013_7203.h5 on the same env.
 **"ValueError: bad marshal data (unknown type code)"**

Also, when I test your method on RAF-DB test set using AffectNet_6336.h5 model, I get 0.67 as the accuracy which doesn't match the reported one in the paper. Is it because I have to use RafDB_8696.h5 model for testing on Raf_DB test set?
Please advise.
Thanks.

**Comment by aliprf** [comment]
Hi.
"ValueError: bad marshal data (unknown type code)" generally is related to the version of the TF you use.

 Regarding the accuracy score, please follow the paper for all technical details.

**Comment by aliprf** [comment]
Due to the difference between the dataset, the accuracy of a model trained on AffectNet, might not be as high, when you tested on other dataset. You need to first fine-tune the model
