### ISSUE TITLE
value error while using pre-trained model

### ISSUE THREAD

**Issue by SeoyunKMLA** [aliprf/Ad-Corre#3]
I tried to use the pre-trained model after I downloaded the .h5 file in the GitHub

but it keeps says that ValueError: bad marshal data (unknown type code)

what's wrong? do I need to download the additional file? or adjusting the version of python or other libraries? 

and here's the code that I want to apply: basically determining the emotion with the webcam

`# Xception Final

import cv2
import numpy as np
from keras.models import load_model
import tensorflow as tf

def f1_metric(y_true, y_pred):
    y_pred = tf.round(y_pred)
    f1 = 2 * tf.reduce_sum(y_true * y_pred) / (tf.reduce_sum(y_true) + tf.reduce_sum(y_pred) + 1e-10)
    return f1

# Load the trained emotion recognition model. Set the path to your model file.
emotion_model = load_model('Fer2013_7203.h5', custom_objects={"f1_metric": f1_metric})
tf.keras.utils.register_keras_serializable("f1_metric")(f1_metric)

# Load the OpenCV haarcascades for face detection
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

# Initialize the webcam
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()  # Read a video frame
    if not ret:
        break

    # Detect faces in the grayscale frame
    faces = face_cascade.detectMultiScale(frame, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))

    for (x, y, w, h) in faces:
        # Extract the face region from the frame
        face = frame[y:y+h, x:x+w]

        # Resize the face region to match the model's input size (299x299 for Xception)
        face = cv2.resize(face, (224, 224))

        # Convert to RGB color format (Xception requires RGB)
        face = cv2.cvtColor(face, cv2.COLOR_BGR2RGB)

        # Normalize the face image
        face = face / 255.0

        # Make a prediction by passing the preprocessed face to the emotion recognition model
        emotion_prediction = emotion_model.predict(np.expand_dims(face, axis=0))

        # Get the emotion label based on the predicted class
        emotions = ["angry", "disgust", "fear", "happy", "neutral", "sad", "surprise"]
        emotion_label = emotions[np.argmax(emotion_prediction)]

        # Draw a rectangle around the detected face and label the emotion
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
        cv2.putText(frame, emotion_label, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)

    # Display the frame with face detection and emotion recognition
    cv2.imshow("Emotion Recognition", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

`

**Comment by aliprf** [comment]
This problem is related to the version of your Cuda, or TensorFlow.
